-- Private brand data room: cached aggregate insights, per-brand credentials,
-- anonymous access sessions, and aggregate visit tracking.
--
-- All objects are server-only. The public site and partner dashboard access
-- them with service_role after doing their own authorization checks.

create table if not exists public.brand_data_room_accesses (
  id uuid primary key default gen_random_uuid(),
  brand_name text not null check (char_length(btrim(brand_name)) between 2 and 100),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$' and char_length(slug) between 2 and 80),
  password_hash text not null,
  is_active boolean not null default true,
  expires_at timestamptz,
  login_count integer not null default 0 check (login_count >= 0),
  page_view_count integer not null default 0 check (page_view_count >= 0),
  last_access_at timestamptz,
  password_changed_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.brand_data_room_sessions (
  id uuid primary key default gen_random_uuid(),
  access_id uuid not null references public.brand_data_room_accesses(id) on delete cascade,
  token_hash text not null unique check (token_hash ~ '^[a-f0-9]{64}$'),
  client_hash text check (client_hash is null or client_hash ~ '^[a-f0-9]{64}$'),
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  expires_at timestamptz not null,
  check (expires_at > created_at)
);

create table if not exists public.brand_data_room_events (
  id bigint generated by default as identity primary key,
  access_id uuid references public.brand_data_room_accesses(id) on delete set null,
  session_id uuid references public.brand_data_room_sessions(id) on delete set null,
  event_type text not null check (event_type in ('login_success', 'login_failed', 'page_view')),
  client_hash text check (client_hash is null or client_hash ~ '^[a-f0-9]{64}$'),
  occurred_at timestamptz not null default now()
);

create table if not exists public.brand_data_room_snapshots (
  country_code text primary key check (country_code in ('AR', 'UY')),
  payload jsonb not null check (jsonb_typeof(payload) = 'object'),
  refreshed_at timestamptz not null
);

create index if not exists brand_data_room_sessions_access_idx
  on public.brand_data_room_sessions (access_id, expires_at desc);

create index if not exists brand_data_room_sessions_expiry_idx
  on public.brand_data_room_sessions (expires_at);

create index if not exists brand_data_room_events_access_idx
  on public.brand_data_room_events (access_id, occurred_at desc);

create index if not exists brand_data_room_events_rate_limit_idx
  on public.brand_data_room_events (client_hash, occurred_at desc)
  where event_type = 'login_failed';

alter table public.brand_data_room_accesses enable row level security;
alter table public.brand_data_room_sessions enable row level security;
alter table public.brand_data_room_events enable row level security;
alter table public.brand_data_room_snapshots enable row level security;

revoke all on table
  public.brand_data_room_accesses,
  public.brand_data_room_sessions,
  public.brand_data_room_events,
  public.brand_data_room_snapshots
from public, anon, authenticated;

grant select, insert, update, delete on table
  public.brand_data_room_accesses,
  public.brand_data_room_sessions,
  public.brand_data_room_events,
  public.brand_data_room_snapshots
to service_role;

grant usage, select on all sequences in schema public to service_role;

create or replace function public.brand_data_room_touch_access_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists brand_data_room_accesses_touch_updated_at
  on public.brand_data_room_accesses;

create trigger brand_data_room_accesses_touch_updated_at
before update on public.brand_data_room_accesses
for each row execute function public.brand_data_room_touch_access_updated_at();

create or replace function public.brand_data_room_rollup_event()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.access_id is null then
    return new;
  end if;

  if new.event_type = 'login_success' then
    update public.brand_data_room_accesses
       set login_count = login_count + 1,
           last_access_at = greatest(coalesce(last_access_at, new.occurred_at), new.occurred_at)
     where id = new.access_id;
  elsif new.event_type = 'page_view' then
    update public.brand_data_room_accesses
       set page_view_count = page_view_count + 1,
           last_access_at = greatest(coalesce(last_access_at, new.occurred_at), new.occurred_at)
     where id = new.access_id;
  end if;

  return new;
end;
$$;

drop trigger if exists brand_data_room_events_rollup
  on public.brand_data_room_events;

create trigger brand_data_room_events_rollup
after insert on public.brand_data_room_events
for each row execute function public.brand_data_room_rollup_event();

-- Snapshot payloads contain aggregate-only data. Location and demographic
-- groups smaller than 20 people are suppressed to reduce re-identification
-- risk. Reward and partner rankings are business records, not user records.
create or replace function public.refresh_brand_data_room_snapshots()
returns void
language plpgsql
security invoker
set search_path = ''
set statement_timeout = '9min'
as $$
declare
  v_country text;
  v_country_name text;
  v_currency text;
  v_now timestamptz := now();
  v_payload jsonb;
begin
  foreach v_country in array array['AR', 'UY'] loop
    v_country_name := case v_country when 'AR' then 'Argentina' else 'Uruguay' end;
    v_currency := case v_country when 'AR' then 'ARS' else 'UYU' end;

    with
    country_profiles as materialized (
      select
        p.id,
        p.age,
        p.interests,
        p.province,
        p.city,
        p.barrio,
        p.created_at,
        p.last_active_date
      from public.profiles p
      where p.country_code = v_country
    ),
    used_coupons as materialized (
      select
        c.user_id,
        c.reward_id,
        c.partner_id,
        c.used_at,
        c.pasitos_spent,
        c.extra_purchase,
        c.partner_liked,
        r.title as reward_title,
        r.category as reward_category,
        r.original_value,
        p.name as partner_name
      from public.coupons c
      join public.rewards r on r.id = c.reward_id
      join public.partners p on p.id = c.partner_id
      where c.status = 'used'
        and r.country_code = v_country
    ),
    redeemers as materialized (
      select user_id, count(*)::bigint as redemption_count
      from used_coupons
      group by user_id
    ),
    parsed_values as materialized (
      select replace(original_value, ',', '.')::numeric as amount
      from used_coupons
      where btrim(coalesce(original_value, '')) ~ '^[0-9]+([.,][0-9]{1,2})?$'
    )
    select jsonb_build_object(
      'countryCode', v_country,
      'countryName', v_country_name,
      'currency', v_currency,
      'headline', jsonb_build_object(
        'registeredUsers', (select count(*) from country_profiles),
        'activeUsers30d', (select count(*) from country_profiles where last_active_date >= current_date - 29),
        'newUsers30d', (select count(*) from country_profiles where created_at >= v_now - interval '30 days'),
        'redeemingUsers', (select count(*) from redeemers),
        'redemptionsTotal', (select count(*) from used_coupons),
        'redemptions30d', (select count(*) from used_coupons where used_at >= v_now - interval '30 days'),
        'activePartners', (
          select count(*) from public.partners
          where country_code = v_country and is_active = true and approval_status = 'approved'
        ),
        'activeRewards', (
          select count(*) from public.rewards
          where country_code = v_country and is_active = true and type = 'reward'
        ),
        'averageRedeemedValue', (select round(avg(amount), 0) from parsed_values),
        'medianRedeemedValue', (select round(percentile_cont(0.5) within group (order by amount)::numeric, 0) from parsed_values),
        'valueSampleSize', (select count(*) from parsed_values),
        'averagePasitosSpent', (select round(avg(pasitos_spent), 1) from used_coupons)
      ),
      'dataCoverage', jsonb_build_object(
        'ageUsers', (select count(*) from country_profiles where age between 13 and 100),
        'locationUsers', (
          select count(*) from country_profiles
          where nullif(btrim(coalesce(province, '')), '') is not null
             or nullif(btrim(coalesce(city, '')), '') is not null
             or nullif(btrim(coalesce(barrio, '')), '') is not null
        ),
        'interestUsers', (select count(*) from country_profiles where cardinality(interests) > 0)
      ),
      'ageDistribution', coalesce((
        select jsonb_agg(jsonb_build_object('label', label, 'count', count) order by sort_order)
        from (
          select
            case
              when age between 13 and 17 then '13–17'
              when age between 18 and 24 then '18–24'
              when age between 25 and 34 then '25–34'
              when age between 35 and 44 then '35–44'
              when age between 45 and 54 then '45–54'
              when age between 55 and 64 then '55–64'
              when age between 65 and 100 then '65+'
            end as label,
            case
              when age between 13 and 17 then 1
              when age between 18 and 24 then 2
              when age between 25 and 34 then 3
              when age between 35 and 44 then 4
              when age between 45 and 54 then 5
              when age between 55 and 64 then 6
              when age between 65 and 100 then 7
            end as sort_order,
            count(*)::bigint as count
          from country_profiles
          where age between 13 and 100
          group by 1, 2
        ) age_groups
      ), '[]'::jsonb),
      'redeemerAgeDistribution', coalesce((
        select jsonb_agg(jsonb_build_object('label', label, 'count', count) order by sort_order)
        from (
          select
            case
              when cp.age between 13 and 17 then '13–17'
              when cp.age between 18 and 24 then '18–24'
              when cp.age between 25 and 34 then '25–34'
              when cp.age between 35 and 44 then '35–44'
              when cp.age between 45 and 54 then '45–54'
              when cp.age between 55 and 64 then '55–64'
              when cp.age between 65 and 100 then '65+'
            end as label,
            case
              when cp.age between 13 and 17 then 1
              when cp.age between 18 and 24 then 2
              when cp.age between 25 and 34 then 3
              when cp.age between 35 and 44 then 4
              when cp.age between 45 and 54 then 5
              when cp.age between 55 and 64 then 6
              when cp.age between 65 and 100 then 7
            end as sort_order,
            count(*)::bigint as count
          from redeemers rd
          join country_profiles cp on cp.id = rd.user_id
          where cp.age between 13 and 100
          group by 1, 2
        ) age_groups
      ), '[]'::jsonb),
      'locations', jsonb_build_object(
        'provinces', coalesce((
          select jsonb_agg(jsonb_build_object('label', label, 'count', count) order by count desc, label)
          from (
            select min(btrim(province)) as label, count(*)::bigint as count
            from country_profiles
            where nullif(btrim(coalesce(province, '')), '') is not null
            group by lower(btrim(province))
            having count(*) >= 20
            order by count desc
            limit 12
          ) rows
        ), '[]'::jsonb),
        'cities', coalesce((
          select jsonb_agg(jsonb_build_object('label', label, 'count', count) order by count desc, label)
          from (
            select min(btrim(city)) as label, count(*)::bigint as count
            from country_profiles
            where nullif(btrim(coalesce(city, '')), '') is not null
            group by lower(btrim(city))
            having count(*) >= 20
            order by count desc
            limit 12
          ) rows
        ), '[]'::jsonb),
        'neighborhoods', coalesce((
          select jsonb_agg(jsonb_build_object('label', label, 'count', count) order by count desc, label)
          from (
            select min(btrim(barrio)) as label, count(*)::bigint as count
            from country_profiles
            where nullif(btrim(coalesce(barrio, '')), '') is not null
            group by lower(btrim(barrio))
            having count(*) >= 20
            order by count desc
            limit 15
          ) rows
        ), '[]'::jsonb)
      ),
      'redeemerNeighborhoods', coalesce((
        select jsonb_agg(jsonb_build_object('label', label, 'count', count) order by count desc, label)
        from (
          select min(btrim(cp.barrio)) as label, count(*)::bigint as count
          from redeemers rd
          join country_profiles cp on cp.id = rd.user_id
          where nullif(btrim(coalesce(cp.barrio, '')), '') is not null
          group by lower(btrim(cp.barrio))
          having count(*) >= 20
          order by count desc
          limit 12
        ) rows
      ), '[]'::jsonb),
      'interests', coalesce((
        select jsonb_agg(jsonb_build_object('label', label, 'count', count) order by count desc, label)
        from (
          select min(btrim(interest)) as label, count(*)::bigint as count
          from country_profiles cp
          cross join lateral unnest(cp.interests) interest
          where nullif(btrim(interest), '') is not null
          group by lower(btrim(interest))
          having count(*) >= 20
          order by count desc
          limit 15
        ) rows
      ), '[]'::jsonb),
      'redeemerInterests', coalesce((
        select jsonb_agg(jsonb_build_object('label', label, 'count', count) order by count desc, label)
        from (
          select min(btrim(interest)) as label, count(*)::bigint as count
          from redeemers rd
          join country_profiles cp on cp.id = rd.user_id
          cross join lateral unnest(cp.interests) interest
          where nullif(btrim(interest), '') is not null
          group by lower(btrim(interest))
          having count(*) >= 20
          order by count desc
          limit 15
        ) rows
      ), '[]'::jsonb),
      'favoriteCategories', coalesce((
        select jsonb_agg(jsonb_build_object('label', label, 'count', count) order by count desc, label)
        from (
          select
            min(coalesce(cc.label, initcap(replace(p.category, '_', ' ')))) as label,
            count(*)::bigint as count
          from public.user_favorites uf
          join public.partners p
            on uf.item_type = 'partner'
           and uf.item_id ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
           and p.id = uf.item_id::uuid
          left join public.catalog_categories cc on cc.id = p.category
          where p.country_code = v_country
          group by p.category
          having count(*) >= 20
          order by count desc
          limit 12
        ) rows
      ), '[]'::jsonb),
      'redemptionCategories', coalesce((
        select jsonb_agg(jsonb_build_object('label', label, 'count', count) order by count desc, label)
        from (
          select
            min(coalesce(cc.label, initcap(replace(uc.reward_category, '_', ' ')))) as label,
            count(*)::bigint as count
          from used_coupons uc
          left join public.catalog_categories cc on cc.id = uc.reward_category
          group by uc.reward_category
          order by count desc
          limit 12
        ) rows
      ), '[]'::jsonb),
      'redemptionTrend', coalesce((
        select jsonb_agg(
          jsonb_build_object(
            'month', to_char(month_start, 'YYYY-MM'),
            'count', coalesce(redemptions, 0)
          ) order by month_start
        )
        from (
          select months.month_start, count(uc.used_at)::bigint as redemptions
          from generate_series(
            date_trunc('month', v_now) - interval '11 months',
            date_trunc('month', v_now),
            interval '1 month'
          ) months(month_start)
          left join used_coupons uc
            on uc.used_at >= months.month_start
           and uc.used_at < months.month_start + interval '1 month'
          group by months.month_start
        ) trend
      ), '[]'::jsonb),
      'redemptionFrequency', coalesce((
        select jsonb_agg(jsonb_build_object('label', label, 'count', count) order by sort_order)
        from (
          select
            case
              when redemption_count = 1 then '1 canje'
              when redemption_count between 2 and 3 then '2–3 canjes'
              when redemption_count between 4 and 9 then '4–9 canjes'
              else '10+ canjes'
            end as label,
            case
              when redemption_count = 1 then 1
              when redemption_count between 2 and 3 then 2
              when redemption_count between 4 and 9 then 3
              else 4
            end as sort_order,
            count(*)::bigint as count
          from redeemers
          group by 1, 2
        ) frequency
      ), '[]'::jsonb),
      'topRewards', coalesce((
        select jsonb_agg(
          jsonb_build_object('label', reward_title, 'partner', partner_name, 'count', count)
          order by count desc, reward_title
        )
        from (
          select reward_id, min(reward_title) as reward_title, min(partner_name) as partner_name, count(*)::bigint as count
          from used_coupons
          group by reward_id
          order by count desc
          limit 10
        ) rows
      ), '[]'::jsonb),
      'topPartners', coalesce((
        select jsonb_agg(jsonb_build_object('label', partner_name, 'count', count) order by count desc, partner_name)
        from (
          select partner_id, min(partner_name) as partner_name, count(*)::bigint as count
          from used_coupons
          group by partner_id
          order by count desc
          limit 10
        ) rows
      ), '[]'::jsonb),
      'survey', jsonb_build_object(
        'responses', (select count(*) from used_coupons where extra_purchase is not null),
        'extraPurchases', (select count(*) from used_coupons where extra_purchase = true),
        'likedResponses', (select count(*) from used_coupons where partner_liked is not null),
        'liked', (select count(*) from used_coupons where partner_liked = true)
      )
    ) into v_payload;

    insert into public.brand_data_room_snapshots (country_code, payload, refreshed_at)
    values (v_country, v_payload, v_now)
    on conflict (country_code) do update
      set payload = excluded.payload,
          refreshed_at = excluded.refreshed_at;
  end loop;
end;
$$;

revoke all on function public.brand_data_room_touch_access_updated_at() from public, anon, authenticated;
revoke all on function public.brand_data_room_rollup_event() from public, anon, authenticated;
revoke all on function public.refresh_brand_data_room_snapshots() from public, anon, authenticated;
grant execute on function public.refresh_brand_data_room_snapshots() to service_role;

comment on table public.brand_data_room_snapshots is
  'Server-only aggregate, anonymized brand insights. Refreshed exactly five times per UTC day.';

comment on table public.brand_data_room_events is
  'Minimal private access telemetry: logins, failed attempts, and page views. No raw IP address is stored.';

do $$
declare
  existing_job_id bigint;
begin
  select jobid into existing_job_id
  from cron.job
  where jobname = 'refresh-brand-data-room-snapshots';

  if existing_job_id is not null then
    perform cron.unschedule(existing_job_id);
  end if;
end;
$$;

select cron.schedule(
  'refresh-brand-data-room-snapshots',
  '0 2,7,12,17,22 * * *',
  'select public.refresh_brand_data_room_snapshots()'
);

-- Seed both countries immediately so the page is usable before the first cron run.
select public.refresh_brand_data_room_snapshots();
